# -------------------------------------
# GitHub Action - Evgenii Sviridov 2023
# -------------------------------------

name: My-GitHubActions-Basics
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "Flask-Deploy-Ver-${{ github.sha }}"

on: 
  push:
    branches: 
      - main

jobs:
  my-testing:  
    runs-on: Ubuntu-Latest

    steps:
      - name: Print Hello Message
        run: echo "Hello World from Testing job"
        
      - name: Execute few commands
        run: 
          echo "Hello Message 1"
          echo "Hello Message 2"
          echo "Application name: ${{ env.APPLICATION_NAME }}"


  my-deploy:  
    runs-on: Ubuntu-Latest
    needs: [my-testing]

    steps:
      - name: Print Hello Message
        run: echo "Hello World from Deploy job"

      - name: Printing Deployment Package
        run: 
          echo "Deploy package name is: ${{ env.DEPLOY_PACKAGE_NAME }}"
         
